steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/[PROJECT-ID]/coastal-canopy', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/[PROJECT-ID]/coastal-canopy']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'coastal-canopy',
           '--image', 'gcr.io/coastalcanopy-454604/coastal-canopy',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--memory', '2G',
           '--allow-unauthenticated']